### ISSUE TITLE
trying to launch Argo on iOS, get fatal error

### ISSUE THREAD

**Issue by tkkonline** [getargo/app#2]
Hi Paul, 

I'm trying to follow your instructions and launch Argo, i get the following fatal error on iOS when i attempt to open the app. This is AFTER i've changed the security permissions on mac to allow Argo to run:

Fatal error: Uncaught TypeError: Return value of Capsule\Di\Definition::instantiate() must be an instance of Capsule\Di\object, instance of SapiRequest returned in /private/var/folders/6r/mgcq2kb50vvf7_m14rk3gs_00000gn/T/AppTranslocation/48187BEA-8ED2-47B9-B069-BEF71CBB4954/d/Argo.app/Contents/Resources/app/php/vendor/capsule/di/src/Definition.php:87 Stack trace: #0 /private/var/folders/6r/mgcq2kb50vvf7_m14rk3gs_00000gn/T/AppTranslocation/48187BEA-8ED2-47B9-B069-BEF71CBB4954/d/Argo.app/Contents/Resources/app/php/vendor/capsule/di/src/Definition.php(68): Capsule\Di\Definition->instantiate(Object(Capsule\Di\Container)) #1 /private/var/folders/6r/mgcq2kb50vvf7_m14rk3gs_00000gn/T/AppTranslocation/48187BEA-8ED2-47B9-B069-BEF71CBB4954/d/Argo.app/Contents/Resources/app/php/vendor/capsule/di/src/Container.php(47): Capsule\Di\Definition->new(Object(Capsule\Di\Container)) #2 /private/var/folders/6r/mgcq2kb50vvf7_m14rk3gs_00000gn/T/AppTranslocation/48187BEA-8ED2-47B9-B069-BEF71CBB4954/d/Argo.app/Contents/Resources/app/php/vendor/cap in /private/var/folders/6r/mgcq2kb50vvf7_m14rk3gs_00000gn/T/AppTranslocation/48187BEA-8ED2-47B9-B069-BEF71CBB4954/d/Argo.app/Contents/Resources/app/php/vendor/capsule/di/src/Definition.php on line 87

I like the philosophy behind what you are trying to do with Argo and hope it becomes viable. But i'm not a professional coder or web-developer and may need some help overcoming the IT obstacles. I've only just joined Github and alot of this is new to me. Hope you can help, and good luck!

**Comment by pmjones** [comment]
THANK YOU THANK YOU THANK YOU for this bug report. I'm so glad that you are trying out Argo, and thanks in advance for your patience.

First: did you install it on an iOS device, like an iPhone or iPad? Or did you install it on a MacOS device, like a MacBook Pro? Either way: do you know which OS version? (On a MacOS device, mouse over to the Apple menu at the top left and select "About This Mac" to see the version.)

**Comment by tkkonline** [comment]
its a 2012 macbook-pro running OS Mojave 10.14.5

**Comment by pmjones** [comment]
Ah, rats, there's the problem -- the minimum MacOS version is Catalina (10.15).

Now, having said that, the reason it's Catalina is that Catalina comes with PHP 7.3, which is what Argo is programmed in.

So, if you can *either* upgrade to Catalina, *or* find a way to install PHP 7.3, you'll be good. Otherwise, not going to work.

Let me know if either of those is an option for you, or not.

**Comment by tkkonline** [comment]
Thankyou! i updated to Catalina and Argo is now opening properly. I still see the bug resurface when trying to make a new page as opposed to a new post, which i hope you can fix. It would be also good to know if there is a way to upload images, or will be in the future, as I intend to have image-based content in blogs or a gallery page. And editing the banner and adjusting fonts would be nice too. If i can get those then i think ill be able to make a useable site from this app.

But i love the simplicity. Well done on your work so far! You mentioned that onsite comments won't likely be an option. But there's two workarounds: 1) a comment-box that posts to the websites' private email address with an option to request permission to post publicly (which de-facto moderates every single comment, a double-win if your concern is filtering out trolls), or 2) using a web-browser with a comment extension, like Dissenter.

regards

**Comment by pmjones** [comment]
> i updated to Catalina and Argo is now opening properly.

Excellent!

>  I still see the bug resurface when trying to make a new page as opposed to a new post, which i hope you can fix.

Good catch. Turns out that is a different bug; I have fixed it, and you'll see that fix in the next release.

> if there is a way to upload images

There is! Click on the "open folder" link in your draft or post, and you'll see the folder for the post in your Finder. Move or copy your image file to that folder in the Finder. Then, back in Argo, you can refer to that image as `![alt text for the image](imageFileName.jpg)` in the Markdown body.

> editing the banner and adjusting fonts would be nice too.

That is actually the focus of the next release; i.e., some better theming capability, without having to build your own custom templates. No ETA on that yet, working on it as I have time.

> i love the simplicity. Well done on your work so far!

Thanks for saying! Still a long way to go, but a decent start.

> [comments suggestions]

Yes, I've thought about those solutions, and others as well -- e.g. instructions on how to integrate Disqus etc, even though I'd rather avoid compromised commenting platforms. They all have their various tradeoffs.

**Comment by tkkonline** [comment]
excellent, looking forward to the next release. Got images working too now. Thanks for all your help.
